server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: calorie-tracker
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calorie_tracker?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# 文件上传配置
file:
  upload:
    path: ./uploads
  access:
    path: /files
    
# MinIO对象存储配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: calorie-images
  domain: http://localhost:9000  # 外部访问域名

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.calorie.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wx:
  miniapp:
    appid: wx44da6eaf8e17aaa7
    secret: 7deb15f179ffb5219d1f89a13e1cd34a
    token: 
    aesKey: 
    msgDataFormat: JSON

# 图像识别API配置
image:
  recognition:
    provider: baidu # 默认使用百度AI识别
    baidu:
      app-id: 6845669
      api-key: 8eC4ue4joApZJ8BHf1cwSLNo
      secret-key: 3y6wQXPv8U5TzhUsfcBdbNDcMlWHIhSD
    azure:
      endpoint: 你的Azure计算机视觉API端点
      key: 你的Azure计算机视觉API密钥

# 自定义JWT配置
jwt:
  secret: calorieTracker20240710SecretKey9527
  expire: 604800 # 7天，单位秒
  header: Authorization 